"""HERMES browser agent."""

from .models import DownloadResult, ElementInfo, ExtractedData, OperationResult, PageHandle
from .tools import (
    close_browser,
    close_page,
    click,
    download_file,
    extract_data,
    fill_form,
    get_page_text,
    navigate,
    open_url,
    register_hermes_tools,
    scroll,
    set_config,
    set_event_bus,
    take_screenshot,
    type_text,
    upload_file,
    wait_for_element,
    HermesError,
)

__all__ = [
    "DownloadResult",
    "ElementInfo",
    "ExtractedData",
    "OperationResult",
    "PageHandle",
    "HermesError",
    "close_browser",
    "close_page",
    "click",
    "download_file",
    "extract_data",
    "fill_form",
    "get_page_text",
    "navigate",
    "open_url",
    "register_hermes_tools",
    "scroll",
    "set_config",
    "set_event_bus",
    "take_screenshot",
    "type_text",
    "upload_file",
    "wait_for_element",
]

TOOL_LIST = [
    "open_url",
    "navigate",
    "click",
    "type_text",
    "fill_form",
    "scroll",
    "take_screenshot",
    "extract_data",
    "download_file",
    "upload_file",
    "wait_for_element",
    "get_page_text",
    "close_page",
    "close_browser",
]
