"""AEGIS system monitor agent."""

from .models import ClipboardContent, CommandResult, GPUInfo, NetworkInterface, NetworkSnapshot, OperationResult, ProcessInfo, SystemSnapshot
from .tools import (
    AegisError,
    cancel_monitor,
    clipboard_read,
    clipboard_write,
    close_application,
    get_environment_variable,
    get_network_info,
    get_process,
    get_system_info,
    kill_process,
    list_processes,
    monitor_resource,
    open_application,
    register_aegis_tools,
    run_shell_command,
    set_config,
    set_environment_variable,
    set_event_bus,
    take_screenshot,
)

__all__ = [
    "AegisError",
    "ClipboardContent",
    "CommandResult",
    "GPUInfo",
    "NetworkInterface",
    "NetworkSnapshot",
    "OperationResult",
    "ProcessInfo",
    "SystemSnapshot",
    "cancel_monitor",
    "clipboard_read",
    "clipboard_write",
    "close_application",
    "get_environment_variable",
    "get_network_info",
    "get_process",
    "get_system_info",
    "kill_process",
    "list_processes",
    "monitor_resource",
    "open_application",
    "register_aegis_tools",
    "run_shell_command",
    "set_config",
    "set_environment_variable",
    "set_event_bus",
    "take_screenshot",
]

TOOL_LIST = [
    "get_system_info",
    "list_processes",
    "get_process",
    "kill_process",
    "run_shell_command",
    "open_application",
    "close_application",
    "clipboard_read",
    "clipboard_write",
    "take_screenshot",
    "get_network_info",
    "monitor_resource",
    "cancel_monitor",
    "get_environment_variable",
    "set_environment_variable",
]
